version: '3'
networks:
  webapp:
    driver: bridge
  appdb:
    driver: bridge
services:

  homeassistant:
    restart: unless-stopped
    image: homeassistant/home-assistant
    networks:
      - webapp
      - appdb

    # deal with cases where devices are not always present
    devices:
      - ${DEV_USB0}:/dev/ttyUSB0
      - ${DEV_USB1}:/dev/ttyUSB1
      - ${DEV_ACM0}:/dev/ttyACM0
    # and allow apps to detect their presence easily
    environment:
      - DEV_USB0=${DEV_USB0}
      - DEV_USB1=${DEV_USB1}
      - DEV_ACM0=${DEV_ACM0}
    # credit https://stackoverflow.com/a/56997577

      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    # make docker run in regular user context
    user: ${PUID}:${PUID}
    # and this fixes it to run in a venv inside, avoiding container OS permission issues
    command: /config/docker/run


    volumes:
      - ${CONFDIR}/hass:/config
      - /etc/localtime:/etc/localtime:ro

# leave this to avoid issues if USB device ids switch
      - /dev/serial/by-id/:/dev/serial/by-id/

# credit - https://community.home-assistant.io/t/97994/2
# omitting hardcoded image names as network auto creates aliases
# WARNING: reports of some USB devices failing with privileged: true
#    privileged: true

  postdb:
    restart: unless-stopped
    image: postgres
    volumes:
      - ${DATADIR}/postgresql:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # troubleshooting - https://community.home-assistant.io/t/81388/15
      - TZ=${TZ}
    networks:
      - appdb

  nginx:
    image: library/nginx:alpine
    volumes:
#      - ${CONFDIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CONFDIR}/nginx:/etc/nginx:ro
      - ${DATADIR}/secrets:/secrets:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - webapp

